# Generated by Django 3.1 on 2021-10-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ieee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('published_date', models.TextField()),
                ('published_by', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
